name: App react test
on: workflow_dispatch
jobs:
  test:
    runs-on:ubuntu-latest
    steps:
        - name: CheckOut Code
          uses: actions/checkout@v6
        - name : Install Node V18
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - name: Install
          run: npm install
        - name: Unit Tests
          run: npm run test
