name: App react test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: CheckOut Code
          uses: actions/checkout@v6
        - name : Install Node
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - name: Install
          run: |
            cd app-react
            npm install
        - name: Unit Tests
          run: |
            cd app-react
            npm run test
